
swagger: '2.0'
info:
  title: Inventory MS
  version: "0.1"
  description: Microservice for inventory
consumes:
  - application/json
produces:
  - application/json
basePath: "/api"

paths:

  #create coupon
  /create/coupon:
    post:
      tags: [ Coupon ]
      operationId: app.create_coupon
      parameters:
        - $ref : '#/parameters/coupon_body'
      responses:
        200:
          description: Coupon created

  #create product buy
  /create/product_buy:
    post:
      tags: [ ProductBuy ]
      operationId: app.create_product_buy
      parameters:
        - $ref : '#/parameters/product_buy_body'
      responses:
        200:
          description: Product created
        409:
          description: Product already exists

  #create product rent
  /create/product_rent:
    post:
      tags: [ ProductRent ]
      operationId: app.create_product_rent
      parameters:
        - $ref: '#/parameters/product_rent_body'
      responses:
        200:
          description: Product created
        409:
          description: Product already exists



  #edit product buy
  /edit/product_buy/{product_id}:
    post:
      tags: [ ProductBuy ]
      operationId: app.edit_product_buy
      parameters:
        - $ref: '#/parameters/product_buy_body'
        - $ref: '#/parameters/product_id'
      responses:
        200:
          description: Product edited
        404:
          description: Product not found


  #edit product rent
  /edit/product_rent/{product_id}:
    post:
      tags: [ ProductRent ]
      operationId: app.edit_product_rent
      parameters:
        - $ref: '#/parameters/product_rent_body'
        - $ref: '#/parameters/product_id'
      responses:
        200:
          description: Product edited
        404:
          description: Product not found


  #delete product buy
  /delete/product_buy/{product_id}:
    post:
      tags: [ ProductBuy ]
      operationId: app.delete_product_buy
      parameters:
        - $ref: '#/parameters/product_id'
      responses:
        200:
          description: Product deleted
        404:
          description: Product not found

  #delete product rent
  /delete/product_rent/{product_id}:
    post:
      tags: [ ProductRent ]
      operationId: app.delete_product_rent
      parameters:
        - $ref: '#/parameters/product_id'
      responses:
        200:
          description: Product deleted
        404:
          description: Product not found

  #set product buy discount
  /set/product_buy_discount/{product_id}/{discount_percentage}/{valid_until}:
    post:
      tags: [ ProductBuy ]
      operationId: app.set_product_buy_discount
      parameters:
        - $ref: '#/parameters/product_id'
        - $ref: '#/parameters/discount_percentage'
        - $ref: '#/parameters/valid_until'
      responses:
        200:
          description: Product discount set
        404:
          description: Product not found

  #set product rent discount
  /set/product_rent_discount/{product_id}/{discount_percentage}/{valid_until}:
    post:
      tags: [ ProductRent ]
      operationId: app.set_product_rent_discount
      parameters:
        - $ref: '#/parameters/product_id'
        - $ref: '#/parameters/discount_percentage'
        - $ref: '#/parameters/valid_until'
      responses:
        200:
          description: Product discount set
        404:
          description: Product not found


  #get product buy
  /get/product_buy/{product_id}:
    get:
      tags: [ ProductBuy ]
      operationId: app.get_product_buy
      parameters:
        - $ref: '#/parameters/product_id'
      responses:
        200:
          description: Product returned
        404:
          description: Product not found

  #get product rent
  /get/product_rent/{product_id}:
    get:
      tags: [ ProductRent ]
      operationId: app.get_product_rent
      parameters:
        - $ref: '#/parameters/product_id'
      responses:
        200:
          description: Product returned
        404:
          description: Product not found

  #get all products buy
  /get/all_products_buy:
    get:
      tags: [ ProductBuy ]
      operationId: app.get_all_products_buy
      responses:
        200:
          description: Products returned


  #get all products rent
  /get/all_products_rent:
    get:
      tags: [ ProductRent ]
      operationId: app.get_all_products_rent
      responses:
        200:
          description: Products returned


  #search product-buy by name
  /search_product_buy/{search_param}:
    get:
      tags: [ ProductBuy ]
      operationId: app.search_product_buy
      parameters:
        - $ref : '#/parameters/search_param'
      responses:
        200:
          description: Product found
        404:
          description: Product not found

  #search product-rent by name
  /search_product_rent/{search_param}:
    get:
      tags: [ ProductRent ]
      operationId: app.search_product_rent
      parameters:
        - $ref: '#/parameters/search_param'
      responses:
        200:
          description: Product found
        404:
          description: Product not found

  #buy coupon
  /buy_coupon/{coupon_id}:
    get:
      tags: [ Coupon ]
      operationId: app.buy_coupon
      parameters:
        - $ref: '#parameters/coupon_id'
      responses:
        200:
          description: Done
        404:
          description: Coupon not found

  #reserve product_buy
  /reserve_product_buy:
    post:
      tags: [ ReservedProductBuy ]
      operationId: app.reserve_product_buy
      parameters:
        - $ref: '#parameters/reserve_product_buy_body'
      responses:
        200:
          description: Product reserved
        404:
          description: Product not found
        500:
          description: Not enough

  #reserve product_rent
  /reserve_product_rent:
    post:
      tags: [ ReservedProductRent ]
      operationId: app.reserve_product_rent
      parameters:
        - $ref: '#parameters/reserve_product_rent_body'
      responses:
        200:
          description: Product reserved
        404:
          description: Product not found
        500:
          description: Not available

  #confirm buy
  /buy_product/{shopping_cart_id}:
    get:
      tags: [ ReservedProductBuy ]
      operationId: app.buy_product
      parameters:
        - $ref: '#parameters/shopping_cart_id'
      responses:
        200:
          description: Done

  #confirm rent
  /rent_product/{product_id}/{user_id}:
    get:
      tags: [ ReservedProductRent ]
      operationId: app.rent_product
      parameters:
        - $ref: '#parameters/product_id'
        - $ref: '#parameters/user_id'
      responses:
        200:
          description: Done

  #get price for product_buy
  /get_price_for_product_buy/{product_id}:
    get:
      tags: [ ProductBuy ]
      operationId: app.get_price_for_product_buy
      parameters:
        - $ref: '#parameters/product_id'
      responses:
        200:
          description: Product reserved
        404:
          description: Product not found

  #get price for product_rent
  /get_price_for_product_rent/{product_id}:
    get:
      tags: [ ProductRent ]
      operationId: app.get_price_for_product_rent
      parameters:
        - $ref: '#parameters/product_id'
      responses:
        200:
          description: Product reserved
        404:
          description: Product not found

parameters:

  coupon_body:
    name: coupon_body
    description: Input for Coupon
    in: body
    schema:
      required:
        - type
        - quantity
      properties:
        type:
          type: string
        quantity:
          type: integer

  product_buy_body:
    name: product_buy_body
    description: Input for Product Buy
    in: body
    schema:
      required:
        - name
      properties:
        name:
          type: string
        price:
          type: integer
        description:
          type: string
        image:
          type: string
        category:
          type: string
        brand:
          type: string
        quantity:
          type: integer

  product_rent_body:
    name: product_rent_body
    description: Input for Product Rent
    in: body
    schema:
      required:
        - name
      properties:
        name:
          type: string
        price:
          type: integer
        description:
          type: string
        image:
          type: string
        category:
          type: string
        brand:
          type: string
        available:
          type: boolean


  reserve_product_buy_body:
    name: reserve_product_buy_body
    description: Input for Reserve Product Buy
    in: body
    schema:
      required:
        - product_id
        - shopping_cart_id
        - quantity
      properties:
        product_id:
          type: integer
        shopping_cart_id:
          type: integer
        quantity:
          type: integer

  reserve_product_rent_body:
    name: reserve_product_rent_body
    description: Input for Reserve Product Rent
    in: body
    schema:
      required:
        - product_id
        - user_id
      properties:
        product_id:
          type: integer
        user_id:
          type: integer

  search_param:
    name: search_param
    description: Search param (product name)
    in: path
    type: string
    required: true

  coupon_id:
    name: coupon_id
    description: Coupon ID
    in: path
    type: integer
    required: true

  product_id:
    name: product_id
    description: Product ID
    in: path
    type: integer
    required: true

  shopping_cart_id:
    name: shopping_cart_id
    description: Shopping Cart ID
    in: path
    type: integer
    required: true

  user_id:
    name: user_id
    description: User ID
    in: path
    type: integer
    required: true

  quantity:
    name: quantity
    description: Quantity
    in: path
    type: integer
    required: true

  discount_percentage:
    name: discount_percentage
    description: Discount Percentage
    in: path
    type: integer
    required: true

  valid_until:
    name: valid_until
    description: Discount Valid Until
    in: path
    type: string
    required: true