version: '3.7'

services:

  consul:
    image: consul
    container_name: consul
    ports:
      - "8500:8500"

  inventory-api:
    build:
      context: .
    image: inventory:0.0.1
    container_name: inventory-service
    ports:
      - "5005:5000"

#  payments-api:
#    build:
#      context: ../payments
#    image: payments:0.0.1
#    container_name: payments-service
#    ports:
#      - "5006:5000"
#
#  discounts-api:
#    build:
#      context: ../discounts
#    image: discounts:0.0.1
#    container_name: discounts-service
#    ports:
#      - "5007:5000"
#
#  invoices-api:
#    build:
#      context: ../invoices
#    image: invoices:0.0.1
#    container_name: invoices-service
#    ports:
#      - "5008:5000"
#
#  locations-api:
#    build:
#      context: ../locations
#    image: locations:0.0.1
#    container_name: locations-service
#    ports:
#      - "5009:5000"
#
#  reserve-api:
#    build:
#      context: ../reserve
#    image: reserve:0.0.1
#    container_name: reserve-service
#    ports:
#      - "5010:5000"
#
#  shipping-api:
#    build:
#      context: ../shipping
#    image: shipping:0.0.1
#    container_name: shipping-service
#    ports:
#      - "5011:5000"
#
#  shoppingcart-api:
#    build:
#      context: ../shoppingcart
#    image: shoppingcart:0.0.1
#    container_name: shoppingcart-service
#    ports:
#      - "5012:5000"
#
#  social-api:
#    build:
#      context: ../social
#    image: social:0.0.1
#    container_name: social-service
#    ports:
#      - "5013:5000"

#  statistics-api:
#    build:
#      context: ../statistics
#    image: statistics:0.0.1
#    container_name: statistics-service
#    ports:
#      - "5014:5000"

#  user-api:
#    build:
#      context: ../user
#    image: user:0.0.1
#    container_name: user-service
#    ports:
#      - "5015:5000"


